spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.26.212.131:3306/szml1
    username: szml1

    password: 5539d601c3e3f931

  ai:
    openai:
      api-key: sk-5a8f7a44563e4f4faa0bdfafaa88aa4c