spring:
  application:
    name: Agent_demo
  profiles:
    active: dev
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.limou.agent_demo.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.limou.agent_demo.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn